### ISSUE TITLE
Criterion is not up to date and cause assertion on stderr to fail

### ISSUE THREAD

**Issue by Eldriann** [Epitech/epitest-docker#11]
**Describe the bug**
Criterion is not up to date:
When using `cr_assert_stderr_eq_str("");` in a unit test the test will fail as criterion had a bug. (See https://github.com/Snaipe/Criterion/pull/238 for more information on the bug)

**To Reproduce**
Run
```shell script
docker run -it epitechcontent/epitest-docker:latest /bin/bash
```
Inside the docker image:
Copy the following C code to a file (ex: test.c)
```c
#include <criterion/criterion.h>
#include <criterion/redirect.h>

static void init()
{
    cr_redirect_stderr();
}

Test(test, test, .init=init)
{
    cr_assert_stderr_eq_str("");
}
```
Compile it and run
```shell script
gcc -o unit_tests test.c -lcriterion && ./unit_tests
```

**Expected behavior**
The test should pass but is failing because criterion is not up to date

**Screenshots**
![epitech](https://user-images.githubusercontent.com/33515078/68995828-63277880-0892-11ea-9b46-d4fea190f2e2.png)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux bullseye/sid
 - Docker version: 19.03.4
 - Version: build 9013bf583a

**Additional context**

**Comment by Xephi** [comment]
Fixed by https://github.com/Epitech/epitest-docker/commit/04de62705cf582796e525bf7a70fa73dfc010d60
