### ISSUE TITLE
java-11-openjdk mauvaise version

### ISSUE THREAD

**Issue by gabtoubl-epitech** [Epitech/epitest-docker#28]
**Describe the bug**
Lors de l'etape update-alternative du Dockerfile pour build l'image, la mauvaise version de java est mise et donc fait planter le build.

**To Reproduce**
1. cloner le dépôt
2. Supprimer l'image (docker image rm epitechcontent/epitest-docker)
3. ./build.sh --tag latest -n
4. Erreur: `/usr/lib/jvm/java-11-openjdk-11.0.9.11-0.fc32.x86_64/bin/java has not been configured as an alternative for java`

**Expected behavior**
Le build fonctionne et créé l'image

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker version: 19.03.8 build afacb8b7f0

**Solution :**
![image](https://user-images.githubusercontent.com/65179288/105156018-99eac580-5b0b-11eb-9471-531cb2146bcb.png)

**Comment by Xephi** [comment]
Huum, la solution serait plutôt de fixer la version du paquet java installer pour ne pas que ça se reproduise 🤔 
Si tu peux faire une PR en fixant la version et en changeant les alternatives, on est preneur :)
