### ISSUE TITLE
Cannot clone subdirectories, network configuration issue

### ISSUE THREAD

**Issue by IamBlueSlime** [Epitech/epitest-docker#4]
Hi,

Firstly, I don't know if this issue is related to the docker container of Epitech or the configuration of the Jenkins instance. Please correct me if needed.

For the Arcade project, OOP_ Arcade_2018, we are usine a git subrepository to store our API shared with one other group.

Our project was proceeded by Jenkins and failed to build because the docker wasn't able to reach `git.epitech.eu` (trace attached to this issue).

Is this a network configuration issue or an expected behavior?

Thanks,
Jérémy.

[trace.txt](https://github.com/Epitech/epitest-docker/files/3011863/trace.txt)

**Comment by IamBlueSlime** [comment]
As a temporary fix, I've managed to push a copy of the subrepository but it's just a trashfix. It should be really cool to support officially the usage of subrepository in our projects.

**Comment by Sadikum** [comment]
Hi,

This isn't linked to the docker image. Cloning of your repositories are done before entering the docker image. To clone a repository AND it's submodules one must use the flag `--recurse-submodule` or `--recursive` (depending on the git version), we don't do this by design.
