### ISSUE TITLE
Lib UUID missing

### ISSUE THREAD

**Issue by ajnart** [Epitech/epitest-docker#42]
In #41 you tried to add support for the lib uuid. But it seems that you forgot to upload the updated image to Dockerhub 

EDIT: **The cause of the issue is because the image pushed to dockerhub is devel and not latest.**
![image](https://user-images.githubusercontent.com/49837342/119158053-16f46000-ba56-11eb-881b-22b72856233f.png)

``docker run -it --rm --name epirun -v "$(pwd)"/:/app -w /app docker.io/epitechcontent/epitest-docker:latest /bin/zsh -c make re``
Returns `` fatal error: 'uuid/uuid.h' file not found``

Locally :
``docker run -it --rm --name epirun -v "$(pwd)"/:/app -w /app d/epitest /bin/zsh -c make re``
Compiles just fine (``d/epitest`` is the image built with docker build from this repo)

Thanks in advance. 

Also feel free to merge my PR #30

**Comment by Sadikum** [comment]
The image has now been released. Thank you.
