### ISSUE TITLE
Python 3.10 support ?

### ISSUE THREAD

**Issue by huntears** [Epitech/epitest-docker#52]
Hello,

The docker image is currently on fedora 34, and the python version installed on it is 3.9
I would like to ask if a move to python 3.10 (Which is currently a milestone for fedora 35 and on testing for 34, see [here](https://pagure.io/fesco/issue/2494)), or even an installation of 3.10 alongside 3.9 would be doable.

Python 3.10 does not break anything except some internals of itself (See [here](https://docs.python.org/3/whatsnew/3.10.html)), and is implementing some really nice features, such as structural pattern matching and union types support, which I both normally use a lot.
(The parenthesized context managers are also really cool, even if they are less important than the other two)

Thank you for your answer.

**Comment by huntears** [comment]
Excuse me but is there any updates on this issue ?

**Comment by Sadikum** [comment]
Hi, if it's not required by some project in the curriculum we usually don't change packages version from the default of the Fedora version used.
The next update will be for the next scholar year, which is due by August 2022.
