### ISSUE TITLE
Image not building using the build.sh or docker build

### ISSUE THREAD

**Issue by Pepiloto** [Epitech/epitest-docker#54]
**Describe the bug**
The package `java-11-openjdk-11.0.13.0.8-2.fc34.x86_64` and `java-11-openjdk-devel-11.0.13.0.8-2.fc34.x86_64` aren't found when trying to install them.

**To Reproduce**
1. `./build.sh`

**Expected behavior**
The image should be built.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 21.10 x86_64
 - Docker version: 20.10.14, build a224086

**Comment by Sadikum** [comment]
It has been fixed as of f3434ae.
