### ISSUE TITLE
Missing libconfig++

### ISSUE THREAD

**Issue by Saverio976** [Epitech/epitest-docker#59]
**Describe the bug**
Libconfig++ is needed for the new (old project) raytracer in Tek2

**To Reproduce**
1. Open any .cpp
2. Put the include of libconfig++
3. Compile the file
4. See the error

**Expected behavior**
Possibility to compile the file and deliver the project

**Desktop (please complete the following information):**
 - OS: fedora
 - Docker version: irrelevant 
 - Version: lastest form epitechcontent/epitest-docker

**Additional context**
No

**Comment by Xephi** [comment]
Fixed in Dump 2023/2024
